### /role/create 成功
POST http://127.0.0.1:18083/management-api/role/create
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma
#Authorization: Bearer 9d250d9b6c034a6c88bf4034cdf1d4cc

name=测试角色

### /role/update 成功
POST http://127.0.0.1:18083/management-api/role/update
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

id=14&name=test

### /resource/delete 成功
POST http://127.0.0.1:18083/management-api/role/delete
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

roleId=14

### /role/get 成功
GET http://127.0.0.1:18083/management-api/role/get?roleId=13
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

### /role/list-all 成功
GET http://127.0.0.1:18083/management-api/role/list-all
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

### /role/list 成功
GET http://127.0.0.1:18083/management-api/role/list?roleIds=1,13
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

### /role/page 成功
GET http://127.0.0.1:18083/management-api/role/page?pageNo=1&pageSize=10
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

###

