<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-pms-api</module>
        <module>yudao-module-pms-server</module>
    </modules>
    <artifactId>yudao-module-pms</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        pms 包下，项目管理（Project Management System）。
        例如说：项目、工作事项、迭代、看板、工时和知识库等等
    </description>

</project>
