<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-hrm-api</module>
        <module>yudao-module-hrm-server</module>
    </modules>
    <artifactId>yudao-module-hrm</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        hrm 包下，人力资源管理（Human Resource Management）。
        例如说：员工、考勤、招聘、绩效、薪酬等等
    </description>

</project>
