### /admin/page 成功
GET http://127.0.0.1:18083/management-api/admin/page?pageNo=1&pageSize=10
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

### /admin/create 成功
POST http://127.0.0.1:18083/management-api/admin/create
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

username=admin02&password=buzhidao&name=测试管理员&departmentId=1

### /admin/update 成功
POST http://127.0.0.1:18083/management-api/admin/update
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

id=31&username=admin02&password=buzhidao&name=测试管理员&departmentId=1

### /admin/update-status 成功
POST http://127.0.0.1:18083/management-api/admin/update-status
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

adminId=31&status=1

### /admin/update-status 失败，参数缺失
POST http://127.0.0.1:18083/management-api/admin/update-status
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

adminId=31

### admin/update-status 失败，地址不存在
GET http://127.0.0.1:18083/management-api/admin/update-status---
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

adminId=31&status=sss

###
