package cn.iocoder.mall.systemservice.rpc.errorcode;

import cn.iocoder.common.framework.vo.CommonResult;
import cn.iocoder.mall.systemservice.rpc.errorcode.dto.ErrorCodeAutoGenerateDTO;
import cn.iocoder.mall.systemservice.rpc.errorcode.vo.ErrorCodeVO;

import java.util.Date;
import java.util.List;

public interface ErrorCodeRpc {

    CommonResult<List<ErrorCodeVO>> listErrorCodes(String group, Date minUpdateTime);

    CommonResult<Boolean> autoGenerateErrorCodes(ErrorCodeAutoGenerateDTO autoGenerateDTO);

}
