### /department/create 成功
POST http://127.0.0.1:18083/management-api/department/create
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma
dubbo-tag: {{dubboTag}}

name=测试部门&pid=0&sort=0

### /department/update 成功
POST http://127.0.0.1:18083/management-api/department/update
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

id=1&name=测试部门&pid=0&sort=0

### /resource/delete 成功
POST http://127.0.0.1:18083/management-api/department/delete
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

id=1

### /department/get 成功
GET http://127.0.0.1:18083/management-api/department/get?departmentId=1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

### /department/list 成功
GET http://127.0.0.1:18083/management-api/department/list?departmentIds=1,13
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

### /department/tree 成功
GET http://127.0.0.1:18083/management-api/department/tree
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer yudaoyuanma

###

