ALTER TABLE crm_customer
ADD COLUMN street VARCHAR(255) NULL,
ADD COLUMN city VARCHAR(255) NULL,
ADD COLUMN state VARCHAR(255) NULL,
ADD COLUMN postal_code VARCHAR(255) NULL,
ADD COLUMN country VARCHAR(255) NULL,
ADD COLUMN country_code VARCHAR(255) NULL;
